myFood_WebApp/Controllers/FoodsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using myFood_WebApp.Data;
using myFood_WebApp.Data.Services;
using myFood_WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace myFood_WebApp.Controllers
{
    public class FoodsController : Controller
    {
        private readonly IFoodsService _service;

        public FoodsController(IFoodsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allFoods = await _service.GetAllAsync(n => n.Resturant);
            return View(allFoods);
        }

        //Get: Foods/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var foodDetails = await _service.GetFoodByIdAsync(id);
            return View(foodDetails);

        }

        //Get: Foods/Create
        public async Task<IActionResult> Create()
        {

            var foodDropdownsData = await _service.GetNewFoodDropdownsValues();

            ViewBag.ResturantId = new SelectList(foodDropdownsData.Resutrants, "Id", "Name");

            return View();
        }


        //POST
        [HttpPost]
        public async Task<IActionResult> Create(NewFoodVM food)
        {
            if (!ModelState.IsValid)
            {
                var foodDropdownsData = await _service.GetNewFoodDropdownsValues();
                ViewBag.ResturantId = new SelectList(foodDropdownsData.Resutrants, "Id", "Name");
                return View(food);
            }

            await _service.AddNewFoodAsync(food);
            return RedirectToAction(nameof(Index));

        }
    }
}

myFood_WebApp/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using myFood_WebApp.Data.Cart;
using myFood_WebApp.Data.Services;
using myFood_WebApp.Data.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace myFood_WebApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IFoodsService _foodService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IFoodsService foodsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _foodService = foodsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }
        
        public async Task<IActionResult> Index()
        {
            string userId = "";

            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);

        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddToShoppingCart(int id)
        {
            var item = await _foodService.GetFoodByIdAsync(id);

            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> RemoveFromShoppingCart(int id)
        {
            var item = await _foodService.GetFoodByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = "";
            string userEmailAddress = "";

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

myFood_WebApp/Controllers/ResturantsController.cs
using Microsoft.AspNetCore.Mvc;
using myFood_WebApp.Data;
using myFood_WebApp.Data.Services;
using myFood_WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace myFood_WebApp.Controllers
{
    public class ResturantsController : Controller
    {
        private readonly IResturantsService _service;

        public ResturantsController(IResturantsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allResturants = await _service.GetAllAsync();
            return View(allResturants);
        }

        //Get: Resturants/Create
        public IActionResult Create()
        {
            return View();
        }

        //post: Resturants/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("LogoPicture, Name, Address")]Resturant resturant)
        {
            if (!ModelState.IsValid)
            {
                return View(resturant);
            }
            await _service.AddAsync(resturant);
            return RedirectToAction(nameof(Index));
        }

        //Get: Resturants/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var resturantDetails = await _service.GetByIdAsync(id);

            if (resturantDetails == null)
                return View("NotFound");

            return View(resturantDetails);

        }

        //Get: Resturants/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var resturantDetails = await _service.GetByIdAsync(id);
            if (resturantDetails == null) return View("NotFound");
            return View(resturantDetails);
        }

        //post: Resturants/Create (update)
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, LogoPicture, Name, Address")] Resturant resturant)
        {
            if (!ModelState.IsValid)
            {
                return View(resturant);
            }
            await _service.UpdateAsync(id, resturant);
            return RedirectToAction(nameof(Index));
        }

        //Get: Resturants/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var resturantDetails = await _service.GetByIdAsync(id);
            if (resturantDetails == null) return View("NotFound");
            return View(resturantDetails);
        }

        //post: Resturants/Create (update)
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var resturantDetails = await _service.GetByIdAsync(id);
            if (resturantDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

myFood_WebApp/Views/Shared/NotFound.cshtml
<div class="row">
    <h1 class="offset-md-3">There is nothing to reach here.</h1>
</div>

myFood_WebApp/Views/Shared/_CreateItem.cshtml
@model string;



<div class="text-white float-right mr-3">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle mr-2"></i>Add New</a>
</div>

myFood_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Foods" asp-action="Index">myFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-controller="Foods" asp-action="Index"><i class="bi bi-egg-fried mr-2"></i>Foods</a>
                        </li>

                        <!--Dropdown menu-->
                        <li class="nav-item dropdown">

                            <div class="dropdown ">
                                <button class="btn btn-outline-light text-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear mr-2"></i>Manegement
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-controller="Resturants" asp-action="Index">Resturants</a>
                                    <a class="dropdown-item" asp-controller="Foods" asp-action="Index">Meals</a>
                                </div>
                            </div>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    @*User profile section*@
                    <div class="dropdown">
                        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-badge"></i> Hello User
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="profile-btn">
                            <li>
                                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - myFood
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>